"""add recipe details

Revision ID: 141980cbe7f7
Revises: e382262fcfa7
Create Date: 2026-09-07 16:18:36.311573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141980cbe7f7'
down_revision: Union[str, Sequence[str], None] = 'e382262fcfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.Text(), nullable=False))
    op.add_column('recipes', sa.Column('source_name', sa.String(length=100), nullable=False))
    op.add_column('recipes', sa.Column('source_url', sa.String(length=500), nullable=False))
    op.add_column('recipes', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_url')
    op.drop_column('recipes', 'source_url')
    op.drop_column('recipes', 'source_name')
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###
