"""add unique constraint to recipe source url

Revision ID: 14b3f7b15ee2
Revises: 1708d7765fcc
Create Date: 2026-09-15 21:05:36.785231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b3f7b15ee2'
down_revision: Union[str, Sequence[str], None] = '1708d7765fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_source_url'), 'recipes', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_source_url'), table_name='recipes')
    # ### end Alembic commands ###
