"""add recipe ingredient details

Revision ID: 1708d7765fcc
Revises: 4571a2363e0a
Create Date: 2026-09-14 22:08:33.172614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1708d7765fcc'
down_revision: Union[str, Sequence[str], None] = '4571a2363e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('unit', sa.String(length=100), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('details', sa.String(length=255), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('group', sa.String(length=100), nullable=True))
    op.add_column(
    'recipe_ingredients',
    sa.Column(
        'optional',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'optional')
    op.drop_column('recipe_ingredients', 'group')
    op.drop_column('recipe_ingredients', 'details')
    op.drop_column('recipe_ingredients', 'unit')
    # ### end Alembic commands ###
