"""add recipe preparation fields

Revision ID: e382262fcfa7
Revises: de01b091bba4
Create Date: 2026-09-07 16:07:05.275621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e382262fcfa7'
down_revision: Union[str, Sequence[str], None] = 'de01b091bba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('preparation_time', sa.Integer(), nullable=False))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'preparation_time')
    # ### end Alembic commands ###
